In [32]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Import Data.csv

In [33]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

Hasil dari Data.csv

In [34]:
print(x)

[['Andi' 13.0 65000.0]
 ['Lucy' 20.0 100000.0]
 ['Bon' 5.0 17500.0]
 ['Bon' 10.0 35000.0]
 ['Andi' 10.0 nan]
 ['Lucy' nan 200000.0]
 ['Andi' 14.0 70000.0]
 ['Bon' 12.0 60000.0]
 ['Andi' 4.0 20000.0]
 ['Bon' 40.0 140000.0]]


In [35]:
print(y)

['Yes' 'Yes' 'No' 'Yes' 'Yes' 'No' 'No' 'No' 'Yes' 'Yes']


Menghilangkan Missing Value ('nan')

In [37]:
from sklearn.impute import SimpleImputer
impute = SimpleImputer(missing_values=np.nan, strategy='mean')
impute.fit(x[:, 1:3])
x[:, 1:3] = impute.transform(x[:, 1:3])

In [38]:
print(x)

[['Andi' 13.0 65000.0]
 ['Lucy' 20.0 100000.0]
 ['Bon' 5.0 17500.0]
 ['Bon' 10.0 35000.0]
 ['Andi' 10.0 78611.11111111111]
 ['Lucy' 14.222222222222221 200000.0]
 ['Andi' 14.0 70000.0]
 ['Bon' 12.0 60000.0]
 ['Andi' 4.0 20000.0]
 ['Bon' 40.0 140000.0]]


Encoding Data Atribut

In [39]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [40]:
print(x)

[[1.0 0.0 0.0 13.0 65000.0]
 [0.0 0.0 1.0 20.0 100000.0]
 [0.0 1.0 0.0 5.0 17500.0]
 [0.0 1.0 0.0 10.0 35000.0]
 [1.0 0.0 0.0 10.0 78611.11111111111]
 [0.0 0.0 1.0 14.222222222222221 200000.0]
 [1.0 0.0 0.0 14.0 70000.0]
 [0.0 1.0 0.0 12.0 60000.0]
 [1.0 0.0 0.0 4.0 20000.0]
 [0.0 1.0 0.0 40.0 140000.0]]


Encoding Data Label

In [41]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [42]:
print(y)

[1 1 0 1 1 0 0 0 1 1]


Membagi Data ke Training set dan Test set





In [43]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [44]:
print(x_train)

[[1.0 0.0 0.0 14.0 70000.0]
 [1.0 0.0 0.0 10.0 78611.11111111111]
 [1.0 0.0 0.0 13.0 65000.0]
 [0.0 1.0 0.0 10.0 35000.0]
 [0.0 0.0 1.0 20.0 100000.0]
 [0.0 1.0 0.0 12.0 60000.0]
 [1.0 0.0 0.0 4.0 20000.0]
 [0.0 0.0 1.0 14.222222222222221 200000.0]]


In [45]:
print(x_test)

[[0.0 1.0 0.0 5.0 17500.0]
 [0.0 1.0 0.0 40.0 140000.0]]


In [46]:
print(y_train)

[0 1 1 1 1 0 1 0]


In [47]:
print(y_test)

[0 1]


Scaling Data yang Besar

In [48]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [49]:
print(x_train)

[[1.0 0.0 0.0 0.43277040825877366 -0.1668556741858792]
 [1.0 0.0 0.0 -0.5043564908278945 0.0006755290452868974]
 [1.0 0.0 0.0 0.1984886834871066 -0.2641318567072015]
 [0.0 1.0 0.0 -0.5043564908278945 -0.8477889518351351]
 [0.0 0.0 1.0 1.8384607568887759 0.41680142094205447]
 [0.0 1.0 0.0 -0.03579304128456043 -0.36140803922852377]
 [1.0 0.0 0.0 -1.9100468394578967 -1.139617499399102]
 [0.0 0.0 1.0 0.48483301376358834 2.3623250713685002]]


In [50]:
print(x_test)

[[0.0 1.0 0.0 -1.6757651146862298 -1.1882555906597632]
 [0.0 1.0 0.0 6.524095252322117 1.1950108811126328]]
